# RVC 1, Ch2.1

In [2]:
# Works best with jupyter-notebook

In [3]:
%matplotlib notebook 
# https://ipython.readthedocs.io/en/stable/interactive/magics.html
import numpy as np

from spatialmath import *
from spatialmath.base import *
from roboticstoolbox import *
import matplotlib.pyplot as plt

#!pip3 install sympy testresources pgraph

np.set_printoptions(linewidth=100, formatter={'float': lambda x: f"{x:8.4g}" if abs(x) > 1e-10 else f"{0:8.4g}"})

## Lec 01.6 (Ch 2.1) 2D rotations
*For more help with 2D commands see:*
https://petercorke.github.io/spatialmath-python/func_2d.html

In [4]:
# Rotations about a given axis can be achieved with:
# SO(2) rot2 (ndarray (2,2)) rotation matrices
# SE(2) SE2 creates (ndarray (3,3)) rotation matrices


# Create a rotation matrix
R = rot2(0)
print(R)

[[       1        0]
 [       0        1]]


In [5]:
# Rotate by 0.2 radians
R=rot2(0.2)
print(R)

[[  0.9801  -0.1987]
 [  0.1987   0.9801]]


In [6]:
# Rotate by 30 degrees
R=rot2(30,'deg')
print(R)

[[   0.866     -0.5]
 [     0.5    0.866]]


In [7]:
# Rotation matrices are 
# 1) orthnormal: columns are orthogonal to each other and unit length
# 2) full rank: independent/invertible
# 3) symmetrical: the inverse is equal to the transpose
c1=R[:,0]
c2=R[:,1]

print('Norm c1: ', norm(c1))
print('Norm c2: ', np.linalg.norm(c2))

Norm c1:  1.0
Norm c2:  1.0


In [8]:
# Compute the dot product
np.dot(c1,c2) # np.dot() works with vectors, dot() works with Quaternions
c1.dot(c2)

0.0

In [9]:
# Full rank
np.linalg.det(R) # lnp.lingalg builds on blas/lapack libs. See https://numpy.org/doc/stable/reference/routines.linalg.html

1.0

In [10]:
# Invertible
np.linalg.inv(R)

array([[   0.866,      0.5],
       [    -0.5,    0.866]])

In [11]:
# Symmetrical
R=np.transpose(R)
print(R)

[[   0.866      0.5]
 [    -0.5    0.866]]


In [12]:
# Chains of rotation matrices keep the same properties
np.linalg.det(np.matmul(R,R))

1.0

## Plotting

## Symbolic

In [13]:
# Run as shell command with !
!pip3 install sympy

In [14]:
from spatialmath.base.symbolic import *

In [15]:
theta = symbol('theta')
R=rot2(theta)
print(R)

[[cos(theta) -sin(theta)]
 [sin(theta) cos(theta)]]


In [16]:
R2=np.matmul(R,R)
print(R2)

[[-sin(theta)**2 + cos(theta)**2 -2*sin(theta)*cos(theta)]
 [2*sin(theta)*cos(theta) -sin(theta)**2 + cos(theta)**2]]


In [17]:
np.matmul(R,R)

array([[-sin(theta)**2 + cos(theta)**2, -2*sin(theta)*cos(theta)],
       [2*sin(theta)*cos(theta), -sin(theta)**2 + cos(theta)**2]], dtype=object)

In [18]:
simplify(np.matmul(R,R))

[[cos(2*theta), -sin(2*theta)], [sin(2*theta), cos(2*theta)]]

---
## Lec 01.7 (Ch 2.1) 2D Rotation and Translation

Create a homogenous transformation representation of a pure translation


In [19]:
# https://petercorke.github.io/spatialmath-python/func_2d.html?highlight=transl2#spatialmath.base.transforms2d.transl2
T1 = transl2(1, 2)
print(T1)

[[       1        0        1]
 [       0        1        2]
 [       0        0        1]]


Create a homogenous transformation representation a pure rotation

In [20]:
R1 = rot2(0.5236)
print(R1)
R1 = rot2(30,'deg')
print(R1)

[[   0.866     -0.5]
 [     0.5    0.866]]
[[   0.866     -0.5]
 [     0.5    0.866]]


Combine a 2D homogenous tranformation matrix with a rotation and translation

In [21]:
T1 = transl2(1, 2)@trot2(30, 'deg')
print(T1)

[[   0.866     -0.5        1]
 [     0.5    0.866        2]
 [       0        0        1]]


Special Eucliden SE(2) command can combine the translation and rotation into a homogeneous matrix directly

In [23]:
T1 = SE2(1,2,30, unit='deg') # yields an SE object
print(T1)

T1 = SE2(1,2,0.5236)
print(T1)

   0.866025   -0.5         1            
   0.5         0.866025    2            
   0           0           1            

   0.866025   -0.500001    1            
   0.500001    0.866025    2            
   0           0           1            



In [ ]:
# Setup plotting capabilities for Jupyterlab
# Run as shell command with !
#!pip3 install ipympl

Getting ready to plot. Set the axes

In [ ]:
fig = plt.figure()   # Open a new figure
plt.axes( xlim=(-1,5), ylim=(-1,5) )

In [ ]:
# Create new coordinates
T1 = transl2(1, 2)

Plot the homogenous transform with trplot2

In [ ]:
# https://petercorke.github.io/spatialmath-python/func_2d.html?highlight=trplot#spatialmath.base.transforms2d.trplot2
trplot2(T1, frame='1', color='blue', labels=('x','y'),block=False); # assign color and labels

In [ ]:
# Can also visualize composable transformations
T2 = transl2(2, 1)
trplot2(T2, frame='2', color='red',block=False);

How would a compound transformation T1 followed by T2 look like

In [ ]:
T3 = T1@T2
trplot2(T3, frame='3', color='green', block=False);

In [ ]:
# Create a point W_P wrt to the world
P = np.array([[3],[2]])
plt.scatter(P[0].item(),P[1].item(), c='black',marker='^' );

In [ ]:
# Where, 1_T_W = inv(W_T_1)
# 1_P = 1_T_W * W_P
P1 = np.matmul(np.linalg.inv(T1),e2h(P))
print(P1)

In [ ]:
# Plot the point
plt.scatter( h2e(P1)[0],h2e(P1)[1],c='red');
print(h2e(P1))

In [ ]:
# 2_P = 2_T_W * W_P
P2 = np.matmul(np.linalg.inv(T2),e2h(P))
print(P2)